name: build

on: [push]

env:
  REPO_SLUG: "docker/buildx-bin"
  RELEASE_OUT: "./release-out"

jobs:
  buildkit-edge:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
          buildkitd-flags: --debug
      -
        name: Overlay
        run: |
          ls /sys/module/overlay/parameters/ | while read line ; do echo ${line}: ; cat /sys/module/overlay/parameters/${line} ; done
      -
        name: Test
        run: |
          make test
      -
        name: Build binaries
        run: |
          make release
      -
        name: Post
        run: |
          ls -al /tmp/
          ls -al /var/lib/ /var/lib/buildkit /var/lib/buildkit/runc-overlayfs/ /var/lib/buildkit/runc-overlayfs/snapshots/ /var/lib/buildkit/runc-overlayfs/snapshots/
